-- Seed 04: Activities content library with English + Arabic descriptions.
-- Idempotent: inserts only activities whose name does not already exist.

insert into activities (name, description_en, description_ar, is_active)
select v.name, v.en, v.ar, true
from (values
  ('Motorbike Ride', 'Explore the landscape on a guided motorbike ride along scenic routes.', 'استكشف المناظر الطبيعية في جولة بدراجة نارية بصحبة مرشد على طرق خلابة.'),
  ('Naivasha', 'Visit Lake Naivasha, a tranquil freshwater lake famous for its birdlife and boat safaris.', 'زيارة بحيرة نايفاشا، بحيرة المياه العذبة الهادئة المشهورة بطيورها ورحلات القوارب.'),
  ('Abseiling', 'Descend a cliff face on ropes with professional guides and full safety equipment.', 'النزول على وجه منحدر صخري بالحبال مع مرشدين محترفين ومعدات أمان كاملة.'),
  ('Aquarium Visit', 'Discover colourful marine life up close at the aquarium.', 'اكتشف الحياة البحرية الملوّنة عن قرب في حوض الأسماك.'),
  ('Arrival', 'Arrival and welcome, with meet-and-assist and transfer to your accommodation.', 'الوصول والاستقبال مع المساعدة والنقل إلى مكان إقامتك.'),
  ('Battlesite visit', 'Tour a historic battlefield and hear its stories from a knowledgeable local guide.', 'جولة في ساحة معركة تاريخية والاستماع إلى قصصها مع مرشد محلي خبير.'),
  ('Bridge Walk', 'Cross a scenic suspension bridge with sweeping views over the valley.', 'اعبر جسراً معلقاً خلاباً مع إطلالات واسعة على الوادي.'),
  ('Bungy Jump', 'Take the leap on an adrenaline-filled bungy jump with certified operators.', 'اقفز في تجربة قفز بالحبال المطاطية مليئة بالإثارة مع مشغّلين معتمدين.'),
  ('Bush Breakfast', 'Enjoy a relaxed breakfast in the wild, surrounded by untouched nature.', 'استمتع بإفطار هادئ في البرية محاطاً بطبيعة بكر.'),
  ('Cheetah Tracking', 'Track cheetahs on foot or by vehicle alongside expert wildlife guides.', 'تتبّع الفهود سيراً أو بالمركبة برفقة مرشدي حياة برية خبراء.'),
  ('Coffee tour', 'Walk a working coffee farm and learn the journey from bean to cup with a tasting.', 'تجوّل في مزرعة بنّ عاملة وتعرّف على رحلة البنّ من الحبة إلى الكوب مع تذوّق.'),
  ('Community tours', 'Meet a local community and experience their culture, crafts and daily life.', 'التقِ بمجتمع محلي واختبر ثقافته وحرفه وحياته اليومية.'),
  ('Crocodile Farm Visit', 'Visit a crocodile farm and learn about these reptiles and their conservation.', 'زيارة مزرعة تماسيح والتعرّف على هذه الزواحف وجهود الحفاظ عليها.'),
  ('CrocodileCage-Diving', 'Get face to face with crocodiles from the safety of a submerged cage.', 'قابل التماسيح وجهاً لوجه من داخل قفص غاطس آمن.'),
  ('Cross the Equator', 'Stop at the Equator line for a photo and a fun water-rotation demonstration.', 'توقّف عند خط الاستواء لالتقاط صورة ومشاهدة عرض دوران المياه الممتع.'),
  ('Day hike', 'A guided day hike through scenic trails at a comfortable pace.', 'نزهة سير ليوم كامل عبر مسارات خلابة بوتيرة مريحة بصحبة مرشد.'),
  ('Day walk', 'A gentle guided walk to take in the surroundings and local nature.', 'مشي خفيف بصحبة مرشد للاستمتاع بالمحيط والطبيعة المحلية.'),
  ('Departure', 'Check-out and transfer for your onward departure.', 'إنهاء الإقامة والنقل لمغادرتك.'),
  ('Fishing', 'Spend time fishing on the lake or river with provided equipment.', 'اقضِ وقتاً في الصيد على البحيرة أو النهر مع توفير المعدات.'),
  ('Fly into', 'Scheduled or charter flight into your next destination.', 'رحلة جوية مجدولة أو خاصة إلى وجهتك التالية.'),
  ('Fly out from', 'Scheduled or charter flight out from this destination.', 'رحلة جوية مجدولة أو خاصة للمغادرة من هذه الوجهة.'),
  ('Fly-fishing', 'Try fly-fishing in clear highland streams with a local guide.', 'جرّب الصيد بالذبابة في جداول المرتفعات الصافية مع مرشد محلي.'),
  ('Guided night walk', 'Discover nocturnal wildlife on a guided walk after dark.', 'اكتشف الحياة البرية الليلية في نزهة مسائية بصحبة مرشد.'),
  ('Guided tour', 'A guided tour of the area highlights with a local expert.', 'جولة بصحبة مرشد لأبرز معالم المنطقة مع خبير محلي.'),
  ('Lion and leopard tracking', 'Search for lions and leopards with experienced trackers.', 'البحث عن الأسود والفهود مع متعقّبين ذوي خبرة.'),
  ('Night Game Drive', 'A guided game drive after dark to spot nocturnal animals.', 'رحلة سفاري ليلية بصحبة مرشد لرصد الحيوانات الليلية.'),
  ('Ostrich Farm visit', 'Visit an ostrich farm and learn about these remarkable birds.', 'زيارة مزرعة نعام والتعرّف على هذه الطيور المميزة.'),
  ('Overnight hike', 'A multi-day hike with a wilderness overnight camp.', 'رحلة سير لعدة أيام مع مبيت في مخيم بريّ.'),
  ('Rhino tracking', 'Track rhinos on foot with armed rangers and expert guides.', 'تتبّع وحيد القرن سيراً مع حرّاس مسلّحين ومرشدين خبراء.'),
  ('Rock Art Visit', 'Visit ancient rock art sites and learn their cultural significance.', 'زيارة مواقع الفن الصخري القديم والتعرّف على أهميتها الثقافية.'),
  ('Scenic Drive', 'A relaxed scenic drive through dramatic landscapes.', 'جولة بالسيارة عبر مناظر طبيعية ساحرة بوتيرة هادئة.'),
  ('Scenic flight', 'A light-aircraft scenic flight with breathtaking aerial views.', 'رحلة جوية بطائرة خفيفة مع إطلالات جوية خلابة.'),
  ('Self-Drive Transfer', 'A self-drive transfer between destinations at your own pace.', 'نقل بالقيادة الذاتية بين الوجهات بالوتيرة التي تناسبك.'),
  ('Self-Guided Game Drive', 'Explore the park at your own pace on a self-guided game drive.', 'استكشف المحمية بالوتيرة التي تناسبك في رحلة سفاري ذاتية.'),
  ('Sibebe Rock Guided Walk', 'A guided walk on Sibebe Rock, one of the world''s largest granite domes.', 'نزهة بصحبة مرشد على صخرة سيبيبي، إحدى أكبر القباب الجرانيتية في العالم.'),
  ('Stargazing', 'Take in clear night skies on a guided stargazing session.', 'استمتع بسماء ليلية صافية في جلسة مراقبة نجوم بصحبة مرشد.'),
  ('Surfing', 'Catch the waves with a surfing session for all levels.', 'اركب الأمواج في جلسة ركوب أمواج لجميع المستويات.'),
  ('Swimming', 'Cool off and relax with a swim.', 'انتعش واسترخِ بالسباحة.'),
  ('Take a ferry', 'Cross the water by ferry, enjoying the views along the way.', 'اعبر المياه بالعبّارة مستمتعاً بالمناظر على طول الطريق.'),
  ('Treetop walk', 'Stroll an elevated canopy walkway among the treetops.', 'تجوّل على ممر مرتفع بين قمم الأشجار.'),
  ('Tuk-tuk ride', 'Zip through town the local way on a tuk-tuk ride.', 'تنقّل في المدينة بالطريقة المحلية في جولة بالتوك توك.'),
  ('Village Visit', 'Visit a local village to experience traditional life and hospitality.', 'زيارة قرية محلية لاختبار الحياة التقليدية وكرم الضيافة.'),
  ('Visit the Anti-Poaching Dog Team', 'Meet the anti-poaching dog unit and see how they protect wildlife.', 'التقِ بوحدة كلاب مكافحة الصيد الجائر وشاهد كيف تحمي الحياة البرية.'),
  ('Visit the Northern White Rhinos', 'See the last northern white rhinos and learn about efforts to save them.', 'شاهد آخر وحيدات القرن البيضاء الشمالية وتعرّف على جهود إنقاذها.'),
  ('Walking safari', 'Experience the bush on foot with an armed, expert guide.', 'اختبر البرية سيراً على الأقدام مع مرشد خبير مسلّح.'),
  ('Whale watching (land-based)', 'Watch whales from scenic coastal viewpoints in season.', 'مراقبة الحيتان من مطلّات ساحلية خلابة في موسمها.'),
  ('White-water rafting', 'Tackle exciting rapids on a guided white-water rafting trip.', 'خُض المنحدرات المائية المثيرة في رحلة تجديف بصحبة مرشد.'),
  ('Zip line', 'Soar across the canopy on a thrilling zip line.', 'حلّق عبر الغابة على خط انزلاقي مثير.'),
  ('Border crossing', 'Assisted crossing of the border between countries.', 'عبور الحدود بين الدول مع المساعدة اللازمة.'),
  ('Crater rim hike', 'Hike along a volcanic crater rim with spectacular views.', 'سِر على حافة فوهة بركانية مع إطلالات مذهلة.'),
  ('Hotel Pick Up', 'Pick-up from your hotel by your driver-guide.', 'الاصطحاب من فندقك بواسطة السائق المرشد.'),
  ('Museum visit', 'Explore the region''s history and culture at the museum.', 'استكشف تاريخ المنطقة وثقافتها في المتحف.'),
  ('Picnic Lunch', 'Enjoy a packed picnic lunch in a scenic spot.', 'استمتع بغداء نزهة معبّأ في موقع خلاب.'),
  ('Hotel Drop Off', 'Drop-off at your hotel by your driver-guide.', 'التوصيل إلى فندقك بواسطة السائق المرشد.'),
  ('Guided Game Drive', 'A classic guided game drive in search of wildlife.', 'رحلة سفاري كلاسيكية بصحبة مرشد بحثاً عن الحياة البرية.'),
  ('Day Tour', 'A full-day guided tour of the area''s highlights.', 'جولة بصحبة مرشد ليوم كامل لأبرز معالم المنطقة.'),
  ('Half Day Tour', 'A half-day guided tour of nearby highlights.', 'جولة بصحبة مرشد لنصف يوم لأبرز المعالم القريبة.'),
  ('Relaxing', 'Free time to relax at your own pace.', 'وقت حر للاسترخاء بالوتيرة التي تناسبك.'),
  ('Birding', 'Spot and identify a variety of birds with a specialist guide.', 'رصد وتمييز أنواع متعددة من الطيور مع مرشد متخصص.'),
  ('Balloon Safari', 'Drift over the savannah at sunrise on a hot-air balloon safari.', 'حلّق فوق السافانا عند الشروق في رحلة سفاري بمنطاد الهواء الساخن.'),
  ('Helicopter Flight', 'See the landscape from above on a scenic helicopter flight.', 'شاهد المناظر من الأعلى في رحلة بطائرة هليكوبتر.'),
  ('Hiking', 'A guided hike through scenic terrain.', 'نزهة سير بصحبة مرشد عبر تضاريس خلابة.'),
  ('Horseback Riding', 'Ride through beautiful scenery on a guided horseback excursion.', 'تجوّل عبر مناظر خلابة في رحلة على ظهر الخيل بصحبة مرشد.'),
  ('Mountain Biking', 'Hit the trails on a guided mountain-biking ride.', 'انطلق على المسارات في جولة بالدراجات الجبلية بصحبة مرشد.'),
  ('Cycling', 'Explore the area on a relaxed guided cycling route.', 'استكشف المنطقة في جولة دراجات هادئة بصحبة مرشد.'),
  ('Quad Biking', 'Ride the trails on a quad bike with a guide.', 'انطلق على المسارات بدراجة رباعية بصحبة مرشد.'),
  ('Kayaking', 'Paddle the calm waters by kayak.', 'جدّف في المياه الهادئة بقارب الكاياك.'),
  ('Canoeing', 'A peaceful canoe trip along the water.', 'رحلة كانو هادئة على المياه.'),
  ('Boat Trip', 'A guided boat trip with wildlife and scenery along the shore.', 'رحلة بالقارب بصحبة مرشد لمشاهدة الحياة البرية والمناظر على الضفاف.'),
  ('Rafting', 'A guided rafting trip down the river.', 'رحلة تجديف بصحبة مرشد على النهر.'),
  ('Diving', 'Explore the underwater world on a guided dive.', 'استكشف العالم تحت الماء في غطسة بصحبة مرشد.'),
  ('Snorkeling', 'Snorkel over coral reefs teeming with marine life.', 'غُص بأنبوب التنفس فوق الشعاب المرجانية المليئة بالحياة البحرية.'),
  ('Beach Time', 'Free time to relax and enjoy the beach.', 'وقت حر للاسترخاء والاستمتاع بالشاطئ.'),
  ('Visit', 'A guided visit to a point of interest.', 'زيارة بصحبة مرشد لأحد المعالم.'),
  ('Sightseeing', 'Take in the main sights at a relaxed pace.', 'استمتع بأبرز المعالم بوتيرة هادئة.'),
  ('City Sightseeing', 'See the highlights of the city with a guide.', 'شاهد أبرز معالم المدينة بصحبة مرشد.'),
  ('City Tour', 'A guided tour of the city''s main attractions.', 'جولة بصحبة مرشد لأهم معالم المدينة.'),
  ('Town Sightseeing', 'Explore the character and highlights of the town.', 'استكشف طابع البلدة وأبرز معالمها.'),
  ('Transfer Game Drive', 'A transfer between destinations combined with a game drive.', 'نقل بين الوجهات مع رحلة سفاري في الطريق.'),
  ('Transfer by Air', 'Transfer between destinations by light aircraft.', 'النقل بين الوجهات بطائرة خفيفة.'),
  ('Transfer by Road', 'Transfer between destinations by road with your driver-guide.', 'النقل بين الوجهات براً بصحبة السائق المرشد.'),
  ('Transfer from Airport', 'Transfer from the airport to your accommodation.', 'النقل من المطار إلى مكان إقامتك.'),
  ('Transfer to Airport', 'Transfer from your accommodation to the airport.', 'النقل من مكان إقامتك إلى المطار.'),
  ('Visit the Maasai', 'Visit a Maasai community to experience their culture and traditions.', 'زيارة مجتمع الماساي لاختبار ثقافتهم وتقاليدهم.'),
  ('Early Morning Game Drive', 'An early-morning game drive when wildlife is most active.', 'رحلة سفاري في الصباح الباكر حين تكون الحياة البرية أكثر نشاطاً.'),
  ('Evening Game Drive', 'An evening game drive as the bush comes alive at dusk.', 'رحلة سفاري مسائية حين تدبّ الحياة في البرية عند الغسق.'),
  ('View the great migration', 'Witness the spectacular wildebeest great migration in season.', 'شاهد الهجرة الكبرى المذهلة للحيوانات البرية في موسمها.'),
  ('Wildlife Course', 'A short guided course on local wildlife and ecology.', 'دورة قصيرة بصحبة مرشد عن الحياة البرية والبيئة المحلية.'),
  ('Sundowner', 'Enjoy a sunset drink at a scenic viewpoint.', 'استمتع بمشروب عند الغروب في موقع خلاب.'),
  ('Mountain Climbing', 'A guided mountain climb for keen adventurers.', 'تسلّق جبلي بصحبة مرشد لعشّاق المغامرة.'),
  ('Photo Workshop', 'Improve your wildlife photography with a guided workshop.', 'طوّر مهاراتك في تصوير الحياة البرية في ورشة بصحبة مرشد.'),
  ('Start tour', 'Official start of your tour with a briefing.', 'البداية الرسمية لجولتك مع جلسة تعريفية.'),
  ('Meet & Greet', 'Meet-and-greet on arrival with your representative.', 'استقبال وترحيب عند الوصول مع ممثلكم.'),
  ('End Tour', 'Conclusion of your tour.', 'ختام جولتكم.'),
  ('Guided Walk', 'A guided walk to explore the area on foot.', 'نزهة سير بصحبة مرشد لاستكشاف المنطقة على الأقدام.'),
  ('Picnic', 'A relaxed picnic in a scenic setting.', 'نزهة طعام هادئة في موقع خلاب.'),
  ('Breakfast', 'Breakfast is included.', 'الإفطار مشمول.'),
  ('Lunch', 'Lunch is included.', 'الغداء مشمول.'),
  ('Dinner', 'Dinner is included.', 'العشاء مشمول.')
) as v(name, en, ar)
where not exists (select 1 from activities a where a.name = v.name);
